---
title: "Wissensentdeckung in Datenbanken SoSe 2018"
subtitle: "Lösungsvorschlag Übungsblatt 11"
output: pdf_document
header-includes: 
  - \usepackage{tikz}
  - \usepackage{tikz-qtree}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) # Code wird ausgegeben
library("FSelector")
library("glmnet")
library("rpart")
        # die Pakete muessen gegebenenfalls installiert werden!
```
## Aufgabe 1

### a)
```{r}
housingData <- read.table("housing.csv", header=TRUE, sep = ",")

fit <- lm(formula = LABEL ~., data = housingData)

# https://www.rdocumentation.org/packages/lmvar/versions/1.5.0/topics/cv.lm
X <- as.matrix(housingData[,1:13])
Y <- housingData[,14]
corssValid5 <- cv.glmnet(x = X, y = Y, nfolds = 5)
plot(corssValid5)

```

### b)
```{r}
set.seed(1234)

# Aus https://cran.r-project.org/web/packages/FSelector/FSelector.pdf
evaluator <- function(subset) {
  #k-fold cross validation
  k <- 5
  splits <- runif(nrow(housingData))
  results = sapply(1:k, function(i) {
    test.idx <- (splits >= (i - 1) / k) & (splits < i / k)
    train.idx <- !test.idx
    test <- housingData[test.idx, , drop=FALSE]
    train <- housingData[train.idx, , drop=FALSE]
    tree <- rpart(as.simple.formula(subset, "LABEL"), train)
    error.rate = sum(test$LABEL != predict(tree, test, type="vector")) / nrow(test)
    return(1 - error.rate)
  })
  #print(subset)
  #print(mean(results))
  return(mean(results))
}

fwrdSubset <- forward.search(names(housingData)[-14], evaluator)
fwrdFormula <- as.simple.formula(fwrdSubset, "LABEL")
print(fwrdFormula)

fit <- lm(formula = fwrdFormula, data = housingData)

corssValid5Fwd <- cv.glmnet(x = X, y = Y, nfolds = 5)
plot(corssValid5Fwd)
cat("Das Feature CRIM wird ausgewählt. Der MSE lässt sich aus dem Plot ablesen.")
```

### c)
```{r}
```

### d)
```{r}
```

### e)

### f)

## Aufgabe 2
\begin{table}[]
\begin{tabular}{lllll}
\hline
Algorithmus            & Online & Laufzeit        & Speicher        & Aufgabe        \\ \hline
Naive Bayes            & nein   & $\mathcal O(N)$ & $\mathcal O(K)$ & Klassifikation \\
Random Forest          &        &                 &                 &                \\
Logistische Regression &        &                 &                 &                \\
Neuronales Netzwerk    &        &                 &                 &                \\
K-MEANS                &        &                 &                 &                \\
FP-Growth              &        &                 &                 &                \\ \hline
\end{tabular}
\end{table}

## Aufgabe 3

### a)
```{r}
# http://adv-r.had.co.nz/Environments.html
filepath = "words.txt"
f = file(filepath, "r")
words <- new.env()

while (TRUE) {
  line = readLines(f, n = 1)
  if (length(line) == 0) {
    break
  }
  word <- noquote(line)
  if (is.null(words$word)) { # if line (word) not part of words: add to env.
    words$word <- 1
  }
  else {
    words$word <- words$word + 1 # else: increase count of line (word)
  }
}

words 

close(f)
```

### b)
```{r}
filepath = "words.txt"
f = file(filepath, "r")

while (TRUE) {
  line = readLines(f, n = 1)
  if (length(line) == 0) {
    break
  }
  
  ## TODO: Hier Code einfügen
}

## TODO: Hier Code einfügen

close(f)
```

### c)

### d)
```{r}
filepath = "words.txt"
f = file(filepath, "r")

while (TRUE) {
  line = readLines(f, n = 1)
  if (length(line) == 0) {
    break
  }
  
  ## TODO: Hier Code einfügen
}

## TODO: Hier Code einfügen

close(f)
```